---
apiVersion: v1
kind: ConfigMap

metadata:
  name: discord-env

data:
  DEBUG: "True"
  PORT: "5000"
  LOG_LEVEL: DEBUG
  REDIS_HOST: redis.statesman.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DB: "8"
  SENTRY_ENV: Development
  BUILD_INFO_PATH: /app/build-info.json
