---
apiVersion: v1
kind: ConfigMap

metadata:
  name: discord-env

data:
  DEBUG: "True"
  PORT: "5000"
  LOG_LEVEL: DEBUG
  REDIS_HOST: redis.statesman.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DB: "8"
  SENTRY_ENV: Development
  BUILD_INFO_PATH: /app/build-info.json
  DISCORD_PUBLIC_KEY: "90db5c47d435467d05483c257e356741e3928a5dc977a9935063544f8f5a2eca"
  DISCORD_CLIENT_ID: "716451923737182280"
  DISCORD_SERVER_ID: "561332376995627033"
  LEADER_CONFIGMAP_NAME: "statesman-discord-leader"
  LEADER_WATCHER_SLEEP: "1"
  RABBITMQ_HOST: "rabbitmq.statesman.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "statesman"
  RABBITMQ_EXCHANGE: "statesman"
  RABBITMQ_USER: "statesman-discord"
  RABBITMQ_QUEUE: discord
  RABBITMQ_API_QUEUE: api
