---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule

metadata:
  name: discord

spec:
  host: discord-v1.statesman.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
