---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: statesman

resources:
  - ../../base
  - configmaps.yaml
  - secrets.yaml
  - hpa.yaml
  - pdb.yaml
  - middlewares.yaml
  - destination-rules.yaml
  - virtual-service.yaml
  - ingress.yaml
patchesStrategicMerge:
  - replicas.yaml

commonLabels:
  app: statesman
  version: v1
  component: discord
