---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret

metadata:
  name: discord-credentials
  namespace: statesman

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: discord
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /pilgrimage/statesman/discord/credentials
