__author__ = "Paul Schifferer <paul@schifferers.net>"
"""
constants.py
- Contstants for keys and environment variable names
"""

CLIENT_AUTH_TOKEN = "CLIENT_AUTH_TOKEN"

SENTRY_DSN = "SENTRY_DSN"
SENTRY_ENV = "SENTRY_ENV"

APPLICATION_NAME = "statesman"
PROFILE_KEY = "profile"
JWT_PAYLOAD = "jwt_payload"
CURRENT_USER_ID = "current_user_id"

DISCORD_TOKEN = "DISCORD_TOKEN"
DISCORD_PUBLIC_KEY = "DISCORD_PUBLIC_KEY"
DISCORD_CLIENT_ID = "DISCORD_CLIENT_ID"
DISCORD_CLIENT_SECRET = "DISCORD_CLIENT_SECRET"
DISCORD_SERVER_ID = "DISCORD_SERVER_ID"
DISCORD_COMMANDS_FILE_PATH = "DISCORD_COMMANDS_FILE_PATH"

# configuration
SEGMENT_WRITE_KEY = "SEGMENT_WRITE_KEY"
DEBUG = "DEBUG"
PORT = "PORT"
LOG_LEVEL = "LOG_LEVEL"
DB_HOST = "DB_HOST"
DB_PORT = "DB_PORT"
DB_USER = "DB_USER"
DB_PW = "DB_PW"
DB_NAME = "DB_NAME"
DB_OPTS = "DB_OPTS"
REDIS_HOST = "REDIS_HOST"
REDIS_PORT = "REDIS_PORT"
REDIS_DB = "REDIS_DB"
REDIS_PW = "REDIS_PW"
LOGSTASH_HOST = "LOGSTASH_HOST"
LOGSTASH_DB_PATH = "LOGSTASH_DB_PATH"
LOGSTASH_TRANSPORT = "LOGSTASH_TRANSPORT"
LOGSTASH_PORT = "LOGSTASH_PORT"
SECRET_KEY = "SECRET_KEY"
CSRF_TOKEN = "CSRF_TOKEN"
SESSION_TYPE = "SESSION_TYPE"
BUILD_INFO_PATH = "BUILD_INFO_PATH"
NAMESPACE = "NAMESPACE"
POD = "POD"
RABBITMQ_HOST = "RABBITMQ_HOST"
RABBITMQ_PORT = "RABBITMQ_PORT"
RABBITMQ_VHOST = "RABBITMQ_VHOST"
RABBITMQ_EXCHANGE = "RABBITMQ_EXCHANGE"
RABBITMQ_USER = "RABBITMQ_USER"
RABBITMQ_PASSWORD = "RABBITMQ_PASSWORD"
RABBITMQ_QUEUE = "RABBITMQ_QUEUE"
RABBITMQ_API_QUEUE = "RABBITMQ_API_QUEUE"
RABBITMQ_HEARTBEAT = "RABBITMQ_HEARTBEAT"
RABBITMQ_TIMEOUT = "RABBITMQ_TIMEOUT"

LEADER_CONFIGMAP_NAME = "LEADER_CONFIGMAP_NAME"
LEADER_WATCHER_SLEEP = "LEADER_WATCHER_SLEEP"

DISCORD_API_URL = "DISCORD_API_URL"

LEADER_CONFIGMAP_KEY_COMMANDS_VERSION = "commands_version"

# Discord message flags
MSG_FLAG_CROSSPOSTED = 1 << 0
MSG_FLAG_IS_CROSSPOST = 1 << 1
MSG_FLAG_SUPPRESS_EMBEDS = 1 << 2
MSG_FLAG_SOURCE_MESSAGE_DELETED = 1 << 3
MSG_FLAG_URGENT = 1 << 4
MSG_FLAG_HAS_THREAD = 1 << 5
MSG_FLAG_EPHEMERAL = 1 << 6
MSG_FLAG_LOADING = 1 << 7
MSG_FLAG_FAILED_TO_MENTION_SOME_ROLES_IN_THREAD = 1 << 8
