---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: discord

rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: discord

roleRef:
  apiGroup: ""
  kind: Role
  name: discord
subjects:
  - kind: ServiceAccount
    name: discord
    apiGroup: ""
