---
kind: Service
apiVersion: v1

metadata:
    name: discord-v1

spec:
    selector:
        app: discord-receiver
        version: v1
    type: ClusterIP
    ports:
        - name: api
          port: 5000
          targetPort: api
          protocol: TCP
