---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry

metadata:
  name: discord

spec:
  hosts:
    - api.discord.com
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS

---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry

metadata:
  name: sentry

spec:
  hosts:
    - "*.sentry.io"
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
