---
kind: Service
apiVersion: v1

metadata:
    name: discord-v1

spec:
    selector:
        app: statesman
        version: v1
        component: discord
    type: LoadBalancer
    ports:
        - name: api
          port: 5000
          targetPort: api
